TestStationStatus/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestStationStatusInfrastructure.HubPayload;

namespace TestStationStatus.Models
{
    public class HomeViewModel
    {
        public HttpPostedFileBase[] filesA;
        public HttpPostedFileBase[] filesB;
        public HttpPostedFileBase[] filesA2;
        public HttpPostedFileBase[] filesB2;

        public HomeScreenUpdate Model { get; set; }

        public HomeViewModel()
        {

        }

        public HomeViewModel(HomeViewModel model)
        {
            filesA = model.filesA;
            filesB = model.filesB;
            filesA2 = model.filesA2;
            filesB2 = model.filesB2;
        }


    }
}

TestStationStatus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestStationStatus.Models;
using TestStationStatusInfrastructure;
using TestStationStatusInfrastructure.Service;

namespace TestStationStatus.Controllers
{
    public class HomeController : Controller
    {
        private HomeViewModel _model;

        RefreshClientService _dataUpdatedClient;
        LocalTestDataService _LocalTestDataServiceA1;
        LocalTestDataService _LocalTestDataServiceB1;
        LocalTestDataService _LocalTestDataServiceA2;
        LocalTestDataService _LocalTestDataServiceB2;

        public HomeController(RefreshClientService refreshClientService, 
            LocalTestDataService localTestDataServiceA1,
        LocalTestDataService localTestDataServiceB1,
        LocalTestDataService localTestDataServiceA2,
        LocalTestDataService localTestDataServiceB2)
        {
            _dataUpdatedClient = refreshClientService;
            _LocalTestDataServiceA1 = localTestDataServiceA1;
            _LocalTestDataServiceB1 = localTestDataServiceB1;
            _LocalTestDataServiceA2 = localTestDataServiceA2;
            _LocalTestDataServiceB2 = localTestDataServiceB2;
        }

        public ActionResult Index()
        {
            _model = new HomeViewModel();
            if (_dataUpdatedClient.BackgroundWorker == null)
            {
                //new List<LocalTestDataService> { _LocalTestDataServiceA1, _LocalTestDataServiceB1, _LocalTestDataServiceA2, _LocalTestDataServiceB2 }
                _dataUpdatedClient.StartService();
            }

            while (_dataUpdatedClient.LatestModel==null )
            {
                System.Threading.Thread.Sleep(1000);
            }

            _model.Model = _dataUpdatedClient.LatestModel;

            return View(_model);
        }

        [HttpPost]
        public ActionResult Upload2(int id, HomeViewModel test)
        {
            string IP = Request.UserHostName;
            var file = Request.Files;
            string userName = null;

            if (User != null && User.Identity != null && !string.IsNullOrWhiteSpace(User.Identity.Name))
            {
                userName = User.Identity.Name;
            }

            // Verify that the user selected a file
            _dataUpdatedClient.UploadFile(id, file, IP, userName);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult Cancel(int id, HomeViewModel test)
        {
            _dataUpdatedClient.KillCurrentTestCase(id);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact information.";

            return View();
        }
    }
}

TestStationStatus/Controllers/StatusController.cs
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestStationStatus.Models;
using TestStationStatusInfrastructure;
using TestStationStatusInfrastructure.Service;

namespace TestStationStatus.Controllers
{
    public class StatusController : Controller
    {
        LocalTestDataService _localDataService;
        RefreshClientService _dataUpdatedClient;


        private static StatusViewModel _model;

        public StatusController(RefreshClientService dataUpdatedClient)
        {
            _dataUpdatedClient = dataUpdatedClient;
            _dataUpdatedClient.StartService();
            _localDataService = _dataUpdatedClient.GetLocalTestDataService(0); 
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }

            base.Dispose(disposing);
        }

        public ActionResult Cancel()
        {
            _localDataService.KillCurrentTestCase();
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        public ActionResult Upload(StatusViewModel model, HttpPostedFileBase[] file)
        {
            string IP = Request.UserHostName;
            string userName = null;

            if (User != null && User.Identity != null && !string.IsNullOrWhiteSpace(User.Identity.Name))
            {
                userName = User.Identity.Name;
            }

            // Verify that the user selected a file
            if (file != null && file[0] != null && file[0].ContentLength > 0)
            {
                _localDataService.UploadFile(file, IP, userName);
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        public ActionResult Upload2()
        {
            string IP = Request.UserHostName;
            var file = Request.Files;
            string userName = null;

            if (User != null && User.Identity != null && !string.IsNullOrWhiteSpace(User.Identity.Name))
            {
                userName = User.Identity.Name;
            }

            // Verify that the user selected a file
            if (file != null && file[0] != null && file[0].ContentLength > 0)
            {
                _localDataService.UploadFile(file, IP, userName);
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        // GET: Status
        public ActionResult Index(int? id)
        {
            if (_model == null)
            {
                _model = new StatusViewModel();
            }

            if (_dataUpdatedClient.BackgroundWorker == null)
            {
                _dataUpdatedClient.StartService();
            }
            if (id.HasValue)
            {
                _localDataService = _dataUpdatedClient.GetLocalTestDataService(id.Value);
            }

            var model = _localDataService.GetModelFromLocalFiles();
            _model = new StatusViewModel(model);

            _model.PCName = Environment.MachineName;
            if (id.HasValue)
            {
                _model.PCName = _localDataService.PCName;
            }

            return View(_model);
        }
    }
}

TestStationStatus/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>

<h4>Test case execution</h4>
<p>The application allows any user (test case developer) to queue up their test case and see an estimated completion time based on previous execution.</p>
<h4>Test stations</h4>
<p>The home page is intended to give a high level overview of what the PC is currently doing and what is queued up, so the user can make a decision on where to run their test case.</p>
<h4>Test station status</h4>
<p>This shows a detailed view of the current activity on a test station, this includes the step the current test is running (and recent history), the test cases that are part of the current batch and the test cases in the queue.</p>
<h4>Test reporting</h4>
<p>Since that site is now the hub of ATS test stations, and is able to collect data in a centralised place, this would be a logical places to offer some reporting (features not provided in TeamCity test cases)</p>

<img src="~/Content/Images/DSC_3958.jpg" height="800" width="500" /> 

TestStationStatus/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Landis+Gyr<br />
    <br />
</address>

<address>
    <strong>ATS Guru:</strong>   <a href="mailto:Walter.Rogenmoser@landisgyr.com">Walter.Rogenmoser@landisgyr.com</a><br />
    <strong>Test case expert:</strong> <a href="mailto:david.kitcherside@landisgyr.com">david.kitcherside@landisgyr.com</a>
</address>

TestStationStatus/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model TestStationStatus.Models.HomeViewModel

@section styles
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Home.css")">
}

@section scripts{
    <script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.1.js"></script>
    <script src="~/signalr/hubs"></script>

    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        var monitor;

        $(function () {
            //$.connection.hub.logging = true;

            monitor = $.connection.monitorHub;
            monitor.client.HomeUpdated = HomeUpdated;

            $.connection.hub.start(); // Use parameter for debugging only { transport: 'longPolling' }
        });

        // This function is triggered by the server at regular intervals, the latest data is passed
        // as a parameter, this new data is pushed in the the current html structure
        function HomeUpdated(homeModel) {
            for (i = 0; i < homeModel.Station.length; i++)
            {
                $('#Name' + i).text(homeModel.Station[i].Name);
                $('#Status'+i).text(homeModel.Station[i].Status);
                $('#CurrentScript'+i).text(homeModel.Station[i].CurrentScript);
                $('#CurrentScript'+i).addClass(homeModel.Station[i].ScriptStyle);
            }
        };
    </script>
}



<div>
    <div class="row">
        <img class="image-header" src="~/Content/Images/maxresdefault.jpg" />
    </div>

    <div class="row">
        <div class="col-md-4 image-Status">
            <h2>Status Page @Environment.MachineName</h2>
            <p> </p>
            <p>Hold CTRL to open in a new tab</p>
            @foreach (var station in @Model.Model.Station)
            {
            <!-- Here we have a button for each test station -->
                <p><a class="btn btn-status" href="@Url.Action("Index", "Status")?id=@station.Id">Status Page @station.Name</a></p>
            }
            <p> </p>
            <p><a href="http://ausydvs25:8181/project.html?projectId=Embedded_E420_AutoTest&tab=projectOverview">Team City Results Data</a></p>

            <p><a href="https://landisgyr.atlassian.net/secure/RapidBoard.jspa?rapidView=39&projectKey=ATS&view=detail">JIRA Board</a></p>
        </div>

        <div class="col-md-8 image-cog">
            <h2>Test Case queueing</h2>

            <div class="">
@foreach (var station in @Model.Model.Station)
{
                <!-- Here we have a section for each test station -->
                using (Html.BeginForm("Upload2", "Home", FormMethod.Post, new { enctype = "multipart/form-data", test = Model }))
                {
                    @Html.Hidden("id", @station.Id)
                    <p id="@station.NameId">@station.Name</p>
                        <table>
                            <tr>
                                <td colspan="3" id="@station.StatusId">@station.Status</td>
                            </tr>
                            <tr>
                                <td>Current( or last) Script:</td>
                                <td id="@station.CurrentScriptId" class="@station.ScriptStyle">@station.CurrentScript</td>
                                <td><input class="btn btn-test" type="button" title="Cancel" value="Cancel" onclick="location.href='@Url.Action("Cancel", "Home", new { id = station.Id })'" /></td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="file" name="file" multiple />
                                </td>
                                <td colspan="2"><input class="btn btn-test" type="submit" value="Queue Test Case" /></td>
                            </tr>
                        </table>
                }
    <p> </p>
}
                <p> </p>
            </div>
        </div>

    </div>
</div>